spring:
  application:
    name: hello-kopring

  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    # driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/hellokopring_test_db?autoReconnect=true
    username: root
    password: '1234'
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 10
      jdbc-url: jdbc:mariadb://localhost:3306/hellokopring_test_db?autoReconnect=true
      username: root
      password: '1234'
      data-source-properties:
        rewriteBatchedStatements: true

    flyway:
      enabled: true
      #baseline-on-migrate: true
      baseline-version: V20220421174626
      url: jdbc:mariadb://localhost:3306/hellokopring_test_db?autoReconnect=true
      user: root
      password: '1234'


aws:
  secretsmanager:
    enabled: false
cloud:
  aws:
    stack:
      auto: false
    end-point:
      uri: http://localhost:4566
    region:
      static: ap-northeast-2
    credentials:
      profile-name: fmf # FarmMorningFamily
    s3:
      bucket: hello-kopring-uploaded-files
      path: media-files/

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
