spring:
  application:
    name: hello-kopring

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: on
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mariadb://localhost:3306/hellokopring_db?autoReconnect=true
    username: root
    password: '1234'
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 10
      jdbc-url: jdbc:mariadb://localhost:3306/hellokopring_db?autoReconnect=true
      username: root
      password: '1234'
      data-source-properties:
        rewriteBatchedStatements: true
      connection-test-query: SELECT 1

    flyway:
      enabled: true
      baseline-version: 1.00
      url: jdbc:mariadb://localhost:3306/hellokopring_db?autoReconnect=true
      user: root
      password: '1234'
  redis:
    host: 127.0.0.1
    port: 6379

springdoc:
  api-docs:
    enabled: true
    #path: /v3/api-docs  <-- default
  swagger-ui:
    enabled: true
    persistAuthorization: true
    # path: /swagger-ui.html <-- default

  show-actuator: true
  paths-to-match:
    - /api/**

jwt:
  base64Secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  jwtExpirationMs: 7200000  # 2 hours
  jwtRefreshExpirationMs: 172800000 # 2 days


aws:
  secretsmanager:
    enabled: false
cloud:
  aws:
    stack:
      auto: false
    end-point:
      uri: http://localhost:4566
    region:
      static: ap-northeast-2
    credentials:
      profile-name: fmf # FarmMorningFamily
    s3:
      bucket: hello-kopring-uploaded-files
      path: media-files/

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
management:
  endpoints:
    web:
      path-mapping:
        health: healthcheck
      base-path: /monitor
