spring:
  config:
    activate:
      on-profile: local
  application:
    name: hello-kopring

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: on
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/hellokopring_db?autoReconnect=true
    username: root
    password: '1234'
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 10
      jdbc-url: jdbc:mariadb://localhost:3306/hellokopring_db?autoReconnect=true
      username: root
      password: 1234
      driver-class-name: org.mariadb.jdbc.Driver
      data-source-properties:
        rewriteBatchedStatements: true

    flyway:
      enabled: true
      baseline-on-migrate: true
      baseline-version: 1.00
      url: jdbc:mariadb://localhost:3306/hellokopring_db?autoReconnect=true
      user: root
      password: '1234'

aws:
  secretsmanager:
    enabled: false
cloud:
  aws:
    stack:
      auto: false
    end-point:
      uri: http://localhost:4566
    region:
      static: ap-northeast-2
    credentials:
      profile-name: fmf # FarmMorningFamily
    s3:
      bucket: hello-kopring-uploaded-files
      path: media-files/

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
