spring:
  application:
    name: hello-kopring
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    password: '1234'
    username: root
    url: jdbc:mariadb://localhost:3306/hellokopring_test_db?autoReconnect=true

    hikari:
      data-source-properties:
        rewriteBatchedStatements: 'true'
      maximum-pool-size: '10'
      password: '1234'
      username: root
      jdbc-url: jdbc:mariadb://localhost:3306/hellokopring_test_db?autoReconnect=true
      pool-name: jpa-hikari-pool

    flyway:
      password: '1234'
      user: root
      enabled: true
      baseline-version: V20220421174626
      url: jdbc:mariadb://localhost:3306/hellokopring_test_db?autoReconnect=true

  redis:
    host: 127.0.0.1
    port: '6379'


cloud:
  aws:
    end-point:
      uri: http://localhost:4566
    s3:
      bucket: hello-kopring-uploaded-files
      path: media-files/
    region:
      static: ap-northeast-2
    credentials:
      secret-key: $AWS_SECRET_ACCESS_KEY
      access-key: $AWS_ACCESS_KEY_ID
    stack:
      auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

jwt:
  base64Secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  jwtExpirationMs: '7200000'
  jwtRefreshExpirationMs: '172800000'
