spring:
  application:
    name: hello-kopring

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    # driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/hellokopring_test_db?autoReconnect=true
    username: root
    password: '1234'
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 10
      jdbc-url: jdbc:mariadb://localhost:3306/hellokopring_test_db?autoReconnect=true
      username: root
      password: '1234'
      data-source-properties:
        rewriteBatchedStatements: true

    flyway:
      enabled: true
      #baseline-on-migrate: true
      baseline-version: V20220421174626
      url: jdbc:mariadb://localhost:3306/hellokopring_test_db?autoReconnect=true
      user: root
      password: '1234'
  redis:
    host: 127.0.0.1
    port: 6379


aws:
  secretsmanager:
    enabled: false
cloud:
  aws:
    stack:
      auto: false
    end-point:
      uri: http://localhost:4566
    region:
      static: ap-northeast-2
    credentials:
      profile-name: fmf # FarmMorningFamily
    s3:
      bucket: hello-kopring-uploaded-files
      path: media-files/

jwt:
  base64Secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  jwtExpirationMs: 7200000  # 2 hours
  jwtRefreshExpirationMs: 172800000 # 2 days

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
