on:
  push:
jobs:
  createPullRequest:
    runs-on: ubuntu-latest

    if: startsWith(${{ github.GITHUB_REF_NAME }}, 'FF-')
    steps:
#    - name: Set selected color
#      run: echo $GITHUB_REF_NAME
      #id: random-color-generator
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
#    - name: Create commits
#      uses: actions/checkout@v3
#      run: |
#        git config user.name 'soungryoul.kim'
#        git config user.email 'kimsoungryoul@gmail.com'
#        git config --global --add safe.directory "$GITHUB_WORKSPACE"
#        git

    - name: Login
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Jira Find issue key
      id: jira
      uses: atlassian/gajira-find-issue-key@v2.0.2
      with:
        from: branch

    - name: create PullRequest when push
      # id: autoPullRequest
      run: |
        gh pr create --base main \
                     --title "[${{ steps.jira.outputs.issue }}] ${{ github.ref_name }}" \
                     --body "Update report \
                              - Updated with *today's* date \
                             - 자세한 내용은 Jira 티켓을 확인하세요. \
                             [Ticket 바로가기](${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.jira.outputs.issue }})" \
                     --assignee ${{ github.actor }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#--body "Update report \
#                              - Updated with *today's* date \
#                              - 자세한 내용은 Jira 티켓을 확인하세요. \
#                              [Ticket 바로가기][ ${{ secrets.JIRA_BASE_URL }}/browse/${{steps.jira.output.issue}}]"
#    - id: autoCreatePullRequest
#      name: Create Pull Request
#      uses: peter-evans/create-pull-request@v4.0.2
#      with:
#        base: main
#        token: ${{ secrets.GITHUB_TOKEN }}
#        commit-message: Update report
#        committer: GitHub <noreply@github.com>
#        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
#        signoff: false
#        branch: ${{env.GITHUB_REF_NAME}}
#        delete-branch: false
#        title: '[${{steps.jira.output.issue}}] ${{env.GITHUB_REF_NAME}}'
#        body: |
#          Update report
#          - Updated with *today's* date
#          - 자세한 내용은 Jira 티켓을 확인하세요. [Ticket 바로가기][1]
#
#          [1]: ${{ secrets.JIRA_BASE_URL }}/browse/${{steps.jira.output.issue}}
#        labels: |
#          report
#          automated pr
#        assignees: ${{ github.actor }}
#          #reviewers: peter-evans
#        draft: false
