on:
  push:
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    if: startsWith(${{ GITHUB.ref_name }}, 'FF-')
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: ashley-taylor/regex-property-action@1.2
      id: pr_title
      with:
        value: ${{ GITHUB.ref_name }}
        regex: '[A-Z]+-[0-9]+-'
        replacement: ''
    - name: Login
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Jira Find issue key
      id: jira
      uses: atlassian/gajira-find-issue-key@v2.0.2
      with:
        from: branch

    - name: create PullRequest when you push
      id: autoPullRequest
      run: |
        gh pr create --base main \
                     --title "[${{ steps.jira.outputs.issue }}] ${{ steps.pr_title.outputs.value }}" \
                     --body "- 자세한 내용은 Jira 티켓을 확인하세요. \
                             [Ticket 바로가기](${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.jira.outputs.issue }})" \
                     --assignee ${{ GITHUB.actor }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
