name: PR Lint

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize ]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.6.1
        with:
          # JIRA-111 (PullRequest명 앞에 Jira티켓번호가 반드시 명시되어야한다)
          title-regex: "#[A-Z]+-[0-9]+"
          on-failed-regex-fail-action: true
          on-failed-regex-request-changes: true
          on-failed-regex-create-review: true
          on-failed-regex-comment:
            "Jira티켓번호(ex:AA-111)가 prefix로 명시되어야합니다."
          on-succeeded-regex-dismiss-review-comment:
            "Success!"
          repo-token: "${{ secrets.ACCESS_TOKEN}}"