name: kotlin을 포함한 다양한 Lint 검토
on:
  push:
    branches: [main, FF-*]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
        branch: ${{ GITHUB.ref_name }}

    - name: Lint Code Base
      uses: github/super-linter/slim@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_KOTLIN_ANDROID: false
        VALIDATE_SQLFLUFF: false   # sql lint인데 이거 버그 덩어리 ㅡㅡ
        VALIDATE_DOCKERFILE_HADOLINT: false # dockerfile lint 검사에서 제외합니다.
